export interface CurriculumInfo { id: string; label: string; statuses: string[] }
export interface ArtifactRef { slug: string; path: string; title: string; type: ArtifactType; updated: string | null }
export interface KnowledgeItem { canonicalKey: string; curriculum: string; bank: string; id: string; titleOrQuestion: string; phase: string | null; depth: string | null; sourceFile: string; sourceAnchor: string; prerequisites: string[]; followUps: string[]; scheduledWeeks: number[]; rawSection: string; interviewAnswer: ArtifactRef | null }
export interface CodingItem { canonicalKey: string; curriculum: string; id: string; title: string; track: string; firstExposureWeek: number | null; level: string | null; format: string | null; timeBox: string | null; prompt: string | null; concepts: string[]; complexity: string | null; requiredMastery: string | null; followUps: string[]; sourceFile: string; sourceAnchor: string; rawSection: string; codingReview: ArtifactRef | null }
export interface RoadmapWeek { curriculum: string; weekNumber: number; dateRange: string | null; title: string; knowledgeItems: string[]; codingItems: string[]; tasks: string[]; milestones: string[]; reviewRequirements: string[]; interviewProblems: string[]; sourceFile: string; sourceAnchor: string }
export type ArtifactType = 'interview-answer' | 'coding-review';
export interface ContentPage { curriculum: string; slug: string; path: string; title: string; items: string[]; declaredItems: string[]; item: string | null; created: string | null; updated: string | null; type: ArtifactType; tags: string[]; markdown: string }
export interface SourceDoc { curriculum: string; filename: string; path: string; role: string; title: string; markdown: string; indexedKeys: string[] }
export interface CurriculumIndex { schemaVersion: number; generatedAt: string; curricula: CurriculumInfo[]; knowledgeItems: KnowledgeItem[]; codingItems: CodingItem[]; roadmapWeeks: RoadmapWeek[]; interviewAnswers: ContentPage[]; codingReviews: ContentPage[]; sources: SourceDoc[]; warnings: string[]; errors: string[] }
export interface ItemProgress { completed?: boolean; mastery?: string; attempts?: number; lastAttempt?: string; nextReview?: string; note?: string }
export interface ProgressStore { schemaVersion: 1; items: Record<string, ItemProgress> }
